server:
  host: localhost
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urls?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: musinsa
    password: jiwoo1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
    org.hibernate.SQL: debug